server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: mini-autorizador/api
    version: 1.0.0
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    platform: mysql
    initialization-mode: always

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.ws.client.MessageTracing.received: DEBUG
    org.springframework.ws.client.MessageTracing.sent: DEBUG
    org.springframework.ws.server.MessageTracing.received: DEBUG
    org.springframework.ws.server.MessageTracing.sent: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
  api-docs:
    resolve-schema-properties: true
    show-actuator: true
    enabled: true